#!/bin/bash

#SBATCH --job-name=train
#SBATCH -A cis250010p
#SBATCH --partition=GPU-shared
#SBATCH --gres=gpu:v100-16:1
#SBATCH --time=1:30:00
#SBATCH --output=logs/train.out
#SBATCH --error=logs/train.err
#SBATCH --mail-type=ALL  # Send email on job BEGIN, END, and FAIL
#SBATCH --mail-user=guantonz@andrew.cmu.edu

# Load required modules
module load anaconda3
conda activate jazz_env

# Run the training script
python3 train.py ckpt_dir log_file